/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/clnFsl72oIO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { VideoIcon } from "lucide-react"
import Header from "./header"
import Testmonials from "./testmonials"
import Projects from "./projects"
import Contact from './contact'

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">

      <nav className="flex justify-center gap-4  bg-muted font-md ">
        <Link href="#projects"
          className="hover:underline underline-offset-4" prefetch={false}
        >
          Work
        </Link>
        <Link
          href="#testmonials"
          className="hover:underline underline-offset-4" prefetch={false}
        >
          Testmonials
        </Link>
        <Link
          href="https://blog.tarikwaleed.tech"
          target="_blank"
          className="hover:underline underline-offset-4" prefetch={false}
        >
          Blog
        </Link>
        <Link href="#contact" className="hover:underline underline-offset-4" prefetch={false}>
          Contact
        </Link>
      </nav>


      <main className="flex-1">
        <Header/>
        <Testmonials/>
        <Projects/>
        <Contact/>
      </main>
      <footer className="flex flex-col gap" />
    </div>
  )
}

